obj-$(CONFIG_ARCH_CTR)	+= ctr_gpiointc.o	# hacked in by default

obj-$(CONFIG_CTR_PXI)	+= ctr_pxi.o

obj-$(CONFIG_CTR_SPI)	+= ctr_spi.o
obj-$(CONFIG_CTR_CODEC)	+= ctr_codec.o

obj-$(CONFIG_CTR_I2C)	+= ctr_i2c.o

obj-$(CONFIG_CTR_MCU)	+= mcu/intc.o		# interrupt controller and
obj-$(CONFIG_CTR_MCU)	+= mcu/regulator.o	# regulator are always enabled

obj-$(CONFIG_CTR_MCUACCEL)	+= mcu/accel.o
obj-$(CONFIG_CTR_MCULED)	+= mcu/led.o
obj-$(CONFIG_CTR_MCURTC)	+= mcu/rtc.o
obj-$(CONFIG_CTR_MCUPSY)	+= mcu/powersupply.o
