obj-$(CONFIG_CTR_GPIO)	+= ctr_gpio.o

obj-$(CONFIG_CTR_SDHC)	+= ctr_sdhc.o

obj-$(CONFIG_CTR_PXI)	+= ctr_pxi.o

obj-$(CONFIG_CTR_SPI)	+= ctr_spi.o
obj-$(CONFIG_CTR_CODEC)	+= ctr_codec.o

obj-$(CONFIG_CTR_I2C)	+= ctr_i2c.o

# interrupt controller and regulator are
# always enabled if the MCU is enabled
obj-$(CONFIG_CTR_MCU)	+= mcu/intc.o
obj-$(CONFIG_CTR_MCU)	+= mcu/regulator.o

obj-$(CONFIG_CTR_MCUACCEL)	+= mcu/accel.o
obj-$(CONFIG_CTR_MCULED)	+= mcu/led.o
obj-$(CONFIG_CTR_MCURTC)	+= mcu/rtc.o
obj-$(CONFIG_CTR_MCUPSY)	+= mcu/powersupply.o
